### ISSUE TITLE
Issuing a warning if no usefull package-root found

### ISSUE THREAD

**Issue by ejemba** [seedstack/seed#208]
Seedstack Core Plugin could emit a warning if no other package-root than org.seedstack exist in the kernel. Basically this situation means nothing usefull is scanned.

If not used from archetype, this can happen from time to time.

**Comment by adrienlauer** [comment]
I agree with this suggestion. However I'm recalling why I didn't do it before. The warning will be triggered in all our samples and our hub. Basically any seedstack-only app. 

It may still be acceptable since it will surely help people which have the problem. Another option would be an INFO level log with all the scanned packages instead ? I kinda like the warning idea though so maybe I could add a flag to disable it in our apps.

What do you think, @ejemba (or anyone else) ?

**Comment by ejemba** [comment]
Let just add an internal property to confirm, we are in a seedstack only application that confirm we do not want add another packageRoot. 
Either you add another packageRoot, either you confirm by adding a property ?

my 2 cents.

**Comment by ejemba** [comment]
@adrienlauer ^
