### ISSUE TITLE
Missing servlet dependency

### ISSUE THREAD

**Issue by Sherpard** [seedstack/seed#235]
When a user tries to create a new SecurityFilter, there's no library that provides javax.servlet.Filter interface.
And that's a required implementation to annotate a class as @SecurityFilter 

[Custom Filters](http://seedstack.org/docs/seed/manual/security/#custom-filters)

A workarround is including javax.servlet-api on your pom, 
```xml
<dependency>
	<groupId>javax.servlet</groupId>
	<artifactId>javax.servlet-api</artifactId>
	<version>${java-servlet-version}</version>
	<scope>provided</scope>
</dependency> 
```
But it should be provided by the stack.

**Comment by adrienlauer** [comment]
No it should never be provided by the stack because you may use a different version (SeedStack requires 3.0+) or your web container should provide it to you when running in such environment.

Note how you define it as provided in your own pom so it won't clash with the one of your web container. It is the same for SeedStack.
